[metadata]
name = amr-propositional-translator
version = 0.1.2
description = Rule-based translation from Abstract Meaning Representation to propositional logic
author = Xuyao Feng
url = https://github.com/fxy-1117/amr-to-propositional-logic
license = MIT
license_files = LICENSE
long_description = file: README.md
long_description_content_type = text/markdown

[options]
packages = find:
python_requires = >=3.8
install_requires = penman==1.2.2
include_package_data = True

[options.packages.find]
include = amr_translator

[options.package_data]
amr_translator = resources/propbank/*
